cookbook 'apt', '~> 2.1.1'
cookbook 'build-essential', '~> 1.4.2'
cookbook 'git', '~> 2.6.0'
cookbook 'python', '~> 1.4.2'
cookbook 'openssl', '~> 1.1.0'
cookbook 'ohai', '~> 1.1.12'
cookbook 'rogue', :git => "https://github.com/ROGUE-JCTD/rogue-cookbook.git"
cookbook 'hostsfile', '~> 2.4.1'
cookbook 'database', '~>1.5.2'
cookbook 'java','~> 1.22.0'
cookbook 'tomcat', '~>0.15.2'
cookbook 'postgresql', '~>3.3.4'
cookbook 'nginx', '~>2.0.4'
