cookbook 'apt', '~> 2.1.1'
cookbook 'build-essential', '~> 1.4.2'
cookbook 'git', '~> 2.6.0'
cookbook 'python', '~> 1.4.0'
cookbook 'openssl', '~> 1.1.0'
cookbook 'ohai', '~> 1.1.12'
cookbook 'rogue', :git => "https://github.com/ROGUE-JCTD/rogue-cookbook.git"
cookbook 'geoserver', :path=> 'cookbooks/geoserver'
cookbook 'hostsfile', '~> 2.4.0'
cookbook 'database'
cookbook 'postgis'